server:
  port: 8080

spring:
  application:
    name: loan-mgmt-service
  # ===========================
  # Kafka Configuration
  # ===========================
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: credit-risk-group
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
  # ===========================
  # Database Configuration
  # ===========================
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
  # ===========================
  # H2 Console Configuration
  # ===========================
  h2:
    console:
      enabled: true
      path: /h2-console
  # ===========================
  # JPA / Hibernate Configuration
  # ===========================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Correct place for dialect property


# ===========================
# springwolf Configuration
# ===========================
springwolf:
  # General application information for the AsyncAPI document
  enabled: true
  docket:
    info:
      title: 'Order Processing API'
      version: 1.0.0
      description: 'Order Processing API Demo.'
    # Base package to scan for @AsyncPublisher and @KafkaListener annotations
    base-package: com.spring.kafka
    servers:
      # You can name the server anything you like (e.g., 'kafka-server')
      kafka-server:
        protocol: kafka
        host: ${spring.kafka.bootstrap-servers:localhost:29092}
  plugin:
    kafka:
      publishing:
        # Enable publishing messages from the UI (use with caution in production)
        enabled: true

# ===========================
# Kafka Topic Configuration
# ===========================
loan:
  processing:
    topic-name: loan-process-topic